### PR TITLE
Fix correction of ActiveArea for CFA in DNG decoder

### LINKED ISSUE #11973: X-Trans DNG files with ActiveArea not aligned at CFA boundary rendered with wrong colors
X-Trans has a bayer matrix with 6x6 dimension. If the ActiveArea is not aligned at this boundary, for example `ActiveArea 5 0 200 3000`, darktable shows false colors for such files. In RawTherapee and Adobe Lightroom, the DNG file is displayed correctly.

grafik

This bug happens somewhere in rawspeed when reconstructing the original CFA pattern for position (0, 0).

This is just a tracking issue, we already found some solutions in https://github.com/darktable-org/rawspeed/pull/369.

### PR DESCRIPTION
**Pull request by cytrinox**
This supersedes #369 and fixes https://github.com/darktable-org/darktable/issues/11973.

For DNG files with CFA patterns larger than 2x2, the shifts for CFA are not correctly applied.
To undo the shift, we just need to use the negated values from ActiveArea.

### CODE REVIEW

File: src/librawspeed/decoders/DngDecoder.cpp [hunk 1]
```diff
@@ -206,8 +206,10 @@ void DngDecoder::parseCFA(const TiffIFD* raw) const {
       }))
     ThrowRDE("Error decoding active area");
 
-  mRaw->cfa.shiftRight(aa[1]);
-  mRaw->cfa.shiftDown(aa[0]);
+  // To reverse the ActiveArea modifictions done earlier, we need to
```
Comment (LebedevRI) [inline src/librawspeed/decoders/DngDecoder.cpp:209]: Apologies for continuing to bikesheed, but i still don't quite get the whole picture.
Is the `TiffTag::CFAPATTERN` in DNG specified for `(0,0)`, or for `TiffTag::ACTIVEAREA`?

Additionally, `RawImageData::subFrame()` says:
https://github.com/darktable-org/rawspeed/blob/586d1492492d9df8a7683401f3017c54a770ffce/src/librawspeed/common/RawImage.cpp#L261-L265

Comment (cytrinox) [reply src/librawspeed/decoders/DngDecoder.cpp:209]: CFAPATTERN is specified for ACTIVEAREA.

**Comment by LebedevRI** [comment]
I haven't checked but seems straight-forward.
Thank you.
